[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test" 
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts"
]
optimizer = true
optimizer_runs = 200
# evm_version = "paris"  # Pre-Shanghai EVM version
# solc_version = "0.8.20"  # If you must use 0.8.20+

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
